name: Linting
on:
  push:
    # Run on push to main branch when source files or tests are changed
    branches:
      - main
    paths:
      - src/tests/*.py
      - src/pyMILES/*.py

  pull_request:
    # Run on pull request regardless of directory changed
    branches:
      - main

  workflow_dispatch:
    inputs:
      manualRun:
        description: 'Manual Run'     
        required: true
      tags:
        description: 'Test manual input scenario tags'  

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for testing
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Analyze code with pylint
        run: |
          pylint --reports n --disable C0103,R1720,W0611,R1711,C0303,C0304,C0410,E0401,C0415,W1510,W0612 src/tests src/pyMILES
          pylint $(git ls-files '*.py')